# Generated by Django 5.1.2 on 2024-10-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dlp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caughtmessage",
            name="channel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="caughtmessage",
            name="timestamp",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="caughtmessage",
            name="user_id",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
