# Generated by Django 5.1.2 on 2024-10-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dlp", "0002_caughtmessage_channel_caughtmessage_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caughtmessage",
            name="additional_info",
        ),
        migrations.AddField(
            model_name="caughtmessage",
            name="file_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="caughtmessage",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="caughtmessage",
            name="source_type",
            field=models.CharField(
                choices=[("message", "Message"), ("file", "File")],
                default="message",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="caughtmessage",
            name="channel",
            field=models.CharField(default="unknown_channel", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="caughtmessage",
            name="message_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="caughtmessage",
            name="timestamp",
            field=models.CharField(default="1", max_length=50),
            preserve_default=False,
        ),
    ]
