version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpassword
      MYSQL_ROOT_PASSWORD: localrootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: localuser
      RABBITMQ_DEFAULT_PASS: localpassword

  celery:
    build: .
    container_name: celery
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

  flower:
    image: mher/flower:latest
    ports:
      - "5555:5555"
    environment:
      - FLOWER_PORT=5555
      - CELERY_BROKER_URL=amqp://localuser:localpassword@host.docker.internal:5672
    depends_on:
      - rabbitmq

volumes:
  db_data:
