version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpassword
      MYSQL_ROOT_PASSWORD: localrootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: localuser
      RABBITMQ_DEFAULT_PASS: localpassword

  webserver:
    build: .
    container_name: webserver
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

  dlp_processor:
    build:
      context: ./dlp_processor
      dockerfile: Dockerfile.dlp
    container_name: dlp_processor
    command: python dlp_processor.py
    depends_on:
      - rabbitmq
      - db
      - webserver
    environment:
      RABBITMQ_USER: localuser
      RABBITMQ_PASSWORD: localpassword
      WEBSERVER_API_KEY: ${WEBSERVER_API_KEY}
      WEBSERVER_BASE_URL: ${WEBSERVER_BASE_URL}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
    restart: always

volumes:
  db_data:
