version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpassword
      MYSQL_ROOT_PASSWORD: localrootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: localuser
      RABBITMQ_DEFAULT_PASS: localpassword

volumes:
  db_data:
